INSERT INTO Category(name, description)
VALUES('Cars and motorcycles', 'New and used');

INSERT INTO Category(name, description)
VALUES('Apartments and houses', 'New and used');

INSERT INTO ARTICLE(name, description, price, category_id) VALUES('Tesla Model Y', 'Electric car', 50000, 1);
INSERT INTO ARTICLE(name, description, price, category_id) VALUES('Apartment on the main square', 'Luxury apartment', 500000, 2);
INSERT INTO ARTICLE(name, description, price, category_id) VALUES('House on the beach', 'Vacation house', 5000000, 1);
INSERT INTO ARTICLE(name, description, price, category_id) VALUES('Oldtimer Mercedes X 1800', 'Vintage car', 100000, 2);
insert into ARTICLE (name, description, price, category_id) values ('Lajo', 'Excision of Right Epididymis, Percutaneous Approach', 32.1, 1);
insert into ARTICLE (name, description, price, category_id) values ('Skivee', 'Muscle Perform Assess Neuro Low Back/LE w Orthosis', 29.1, 1);
insert into ARTICLE (name, description, price, category_id) values ('Jatri', 'Dilate L Verteb Art, Bifurc, w 4+ Intralum Dev, Open', 71.0, 1);
insert into ARTICLE (name, description, price, category_id) values ('Browsezoom', 'Removal of Infusion Device from R Knee Jt, Perc Approach', 11.43, 2);
insert into ARTICLE (name, description, price, category_id) values ('Quamba', 'Inspection of Lumbar Vertebral Disc, Percutaneous Approach', 83.95, 1);
insert into ARTICLE (name, description, price, category_id) values ('Chatterpoint', 'Insertion of Ext Fix into R Mandible, Perc Approach', 96.34, 1);
insert into ARTICLE (name, description, price, category_id) values ('Midel', 'Removal of Synth Sub from Cerv Disc, Perc Endo Approach', 49.12, 2);
insert into ARTICLE (name, description, price, category_id) values ('Jaxspan', 'Fluoroscopy of Left Ankle', 94.25, 2);
insert into ARTICLE (name, description, price, category_id) values ('Shuffledrive', 'Replacement of Right Rib with Synth Sub, Perc Endo Approach', 74.13, 1);
insert into ARTICLE (name, description, price, category_id) values ('Eabox', 'Excision of Cecum, Via Natural or Artificial Opening, Diagn', 15.04, 2);
insert into ARTICLE (name, description, price, category_id) values ('Katz', 'Restrict of Ductus Arterio with Intralum Dev, Perc Approach', 84.24, 2);
insert into ARTICLE (name, description, price, category_id) values ('Flipbug', 'Transfer Facial Nerve to Trochlear Nerve, Open Approach', 65.23, 1);
insert into ARTICLE (name, description, price, category_id) values ('Eare', 'Replace of Sup Vena Cava with Nonaut Sub, Perc Endo Approach', 93.44, 2);
insert into ARTICLE (name, description, price, category_id) values ('Voonte', 'Fragmentation in Large Intestine, Open Approach', 41.24, 1);
insert into ARTICLE (name, description, price, category_id) values ('Meevee', 'Insertion of Ext Fix into L Toe Phalanx Jt, Open Approach', 32.34, 2);
insert into ARTICLE (name, description, price, category_id) values ('Plajo', 'Division of Left Thorax Muscle, Perc Endo Approach', 19.95, 1);
insert into ARTICLE (name, description, price, category_id) values ('Feedbug', 'Removal of Traction Apparatus on Right Upper Arm', 80.9, 1);
insert into ARTICLE (name, description, price, category_id) values ('Kwilith', 'Drainage of Left Abdomen Tendon, Perc Endo Approach, Diagn', 79.16, 2);
insert into ARTICLE (name, description, price, category_id) values ('Tavu', 'Occlusion of Left Ureter, Endo', 29.54, 1);
insert into ARTICLE (name, description, price, category_id) values ('Zava', 'Supplement Splenic Artery with Synth Sub, Open Approach', 59.63, 2);
insert into ARTICLE (name, description, price, category_id) values ('Devpulse', 'Supplement L Extraoc Muscle with Nonaut Sub, Perc Approach', 9.81, 1);
insert into ARTICLE (name, description, price, category_id) values ('Jayo', 'Dilation of L Pulm Vein with Intralum Dev, Open Approach', 87.79, 1);
insert into ARTICLE (name, description, price, category_id) values ('Meetz', 'Revision of Nonaut Sub in Lum Disc, Perc Approach', 57.87, 1);
insert into ARTICLE (name, description, price, category_id) values ('Kaymbo', 'Drainage of Prostate, Endo', 5.64, 1);
insert into ARTICLE (name, description, price, category_id) values ('Demivee', 'Extirpation of Matter from Right Ulnar Artery, Perc Approach', 46.61, 1);
insert into ARTICLE (name, description, price, category_id) values ('Realmix', 'Extirpation of Matter from L Innom Vein, Open Approach', 61.42, 1);
insert into ARTICLE (name, description, price, category_id) values ('Izio', 'Replacement of Splenic Vein with Nonaut Sub, Open Approach', 86.75, 1);
insert into ARTICLE (name, description, price, category_id) values ('Rhybox', 'Removal of Int Fix from L Rib, Perc Endo Approach', 9.72, 1);
insert into ARTICLE (name, description, price, category_id) values ('Omba', 'Revision of Autol Sub in R Femur Shaft, Perc Approach', 50.73, 1);
insert into ARTICLE (name, description, price, category_id) values ('Rhynoodle', 'Insertion of Infusion Dev into Hepatic Vein, Open Approach', 69.54, 1);
insert into ARTICLE (name, description, price, category_id) values ('Voolith', 'Bypass L Verteb Vein to Up Vein w Autol Vn, Perc Endo', 15.27, 2);
insert into ARTICLE (name, description, price, category_id) values ('Centimia', 'Inspection of Face, Open Approach', 58.25, 1);
insert into ARTICLE (name, description, price, category_id) values ('Quamba', 'Drainage of Upper Artery, Percutaneous Approach, Diagnostic', 74.03, 1);
insert into ARTICLE (name, description, price, category_id) values ('Katz', 'Revision of Nonaut Sub in L Hip Jt, Perc Endo Approach', 79.16, 1);
insert into ARTICLE (name, description, price, category_id) values ('Devcast', 'Revision of Autol Sub in Urethra, Via Opening', 95.36, 2);
insert into ARTICLE (name, description, price, category_id) values ('Kazio', 'Supplement Mitral Valve fr L AV Vlv w Zooplastic, Perc Endo', 6.55, 1);
insert into ARTICLE (name, description, price, category_id) values ('Yodel', 'Bypass L Temporal Art to Intracran Art w Synth Sub, Open', 82.18, 2);
insert into ARTICLE (name, description, price, category_id) values ('Kwideo', 'Dilation of Left Colic Artery, Bifurcation, Open Approach', 88.33, 2);
insert into ARTICLE (name, description, price, category_id) values ('Zooxo', 'Revision of Drainage Device in Tracheobronchial Tree, Endo', 13.54, 1);
insert into ARTICLE (name, description, price, category_id) values ('Meevee', 'Bypass R Com Iliac Art to R Ext Ilia w Autol Art, Perc Endo', 73.96, 1);
insert into ARTICLE (name, description, price, category_id) values ('Skivee', 'Division of Right Humeral Shaft, Open Approach', 60.75, 2);
insert into ARTICLE (name, description, price, category_id) values ('Skibox', 'Reposition Skull with Ext Fix, Open Approach', 24.96, 1);
insert into ARTICLE (name, description, price, category_id) values ('Shuffletag', 'Other Specified Central Auditory Processing Assessment', 23.33, 2);
insert into ARTICLE (name, description, price, category_id) values ('Mynte', 'Transplantation of Urinary System into POC, Perc Approach', 85.91, 2);
insert into ARTICLE (name, description, price, category_id) values ('Tagopia', 'Insertion of Radioact Elem into R Axilla, Perc Approach', 73.54, 1);
insert into ARTICLE (name, description, price, category_id) values ('Edgewire', 'Bypass Esophagus to Duodenum with Synthetic Substitute, Endo', 76.35, 2);
insert into ARTICLE (name, description, price, category_id) values ('Mydo', 'Insertion of Tissue Expander into Left Nipple, Perc Approach', 97.91, 2);
insert into ARTICLE (name, description, price, category_id) values ('Kimia', 'Reposition Hard Palate, Open Approach', 2.86, 1);
insert into ARTICLE (name, description, price, category_id) values ('Roodel', 'Supplement Right Hand Muscle with Autol Sub, Open Approach', 24.02, 1);
insert into ARTICLE (name, description, price, category_id) values ('Tambee', 'Release Right Thorax Bursa and Ligament, Perc Endo Approach', 83.39, 2);
insert into ARTICLE (name, description, price, category_id) values ('Topiczoom', 'Removal of Drain Dev from R Metatarsophal Jt, Perc Approach', 73.57, 1);
insert into ARTICLE (name, description, price, category_id) values ('Photobug', 'Insertion of Bone Stim into Up Bone, Perc Approach', 16.35, 2);
insert into ARTICLE (name, description, price, category_id) values ('Edgepulse', 'Drainage of Left Femoral Artery, Percutaneous Approach', 1.1, 1);
insert into ARTICLE (name, description, price, category_id) values ('Buzzster', 'Insertion of Neuro Lead into Azygos Vein, Open Approach', 77.72, 1);
insert into ARTICLE (name, description, price, category_id) values ('Quimm', 'Transfuse Nonaut Fresh Plasma in POC, Circ, Perc', 59.39, 1);
insert into ARTICLE (name, description, price, category_id) values ('Photobug', 'Reposition Left Tarsal Joint with Ext Fix, Open Approach', 91.87, 2);
insert into ARTICLE (name, description, price, category_id) values ('Aimbu', 'Reposition Right Sacroiliac Joint, Percutaneous Approach', 64.91, 2);
insert into ARTICLE (name, description, price, category_id) values ('Kwinu', 'Osteopathic Treatment of Sacrum using Fascial Release', 80.24, 2);
insert into ARTICLE (name, description, price, category_id) values ('Jabbersphere', 'Division of Left Foot Bursa and Ligament, Open Approach', 88.48, 1);
insert into ARTICLE (name, description, price, category_id) values ('Fliptune', 'Dilate R Subclav Art, Bifurc, w 2 Drug-elut, Perc', 57.34, 1);
insert into ARTICLE (name, description, price, category_id) values ('Fiveclub', 'Division of Scalp Subcu/Fascia, Open Approach', 13.51, 2);
insert into ARTICLE (name, description, price, category_id) values ('Flipbug', 'Division of Left Frontal Bone, Open Approach', 61.65, 2);
insert into ARTICLE (name, description, price, category_id) values ('Tazz', 'Revision of Ext Fix in L Wrist Jt, Perc Endo Approach', 19.29, 1);
insert into ARTICLE (name, description, price, category_id) values ('Bluezoom', 'Revision of Feeding Dev in Low Intest Tract, Perc Approach', 78.08, 1);
insert into ARTICLE (name, description, price, category_id) values ('Zoomcast', 'Dilation of Upper Esophagus with Intralum Dev, Perc Approach', 6.55, 1);
insert into ARTICLE (name, description, price, category_id) values ('Devpulse', 'Tomo Nucl Med Imag of Low Extrem using Fluorine 18', 52.38, 1);
insert into ARTICLE (name, description, price, category_id) values ('Tanoodle', 'Repair Larynx, Via Natural or Artificial Opening', 26.63, 1);
insert into ARTICLE (name, description, price, category_id) values ('Geba', 'Central Nervous System, Bypass', 14.23, 1);
insert into ARTICLE (name, description, price, category_id) values ('Trilith', 'Revision of Synth Sub in Occip Jt, Perc Endo Approach', 28.67, 2);
insert into ARTICLE (name, description, price, category_id) values ('Meemm', 'ROM/Jt Integrity Assess Neuro Head, Neck w Oth Equip', 15.87, 2);
insert into ARTICLE (name, description, price, category_id) values ('Meevee', 'Drainage of Left Maxilla, Open Approach', 46.75, 2);
insert into ARTICLE (name, description, price, category_id) values ('Feedfire', 'Resection of R Hand Bursa/Lig, Perc Endo Approach', 37.52, 2);
insert into ARTICLE (name, description, price, category_id) values ('Devshare', 'Drainage of Left Hip Joint, Percutaneous Approach, Diagn', 79.3, 1);
insert into ARTICLE (name, description, price, category_id) values ('Jaloo', 'Replacement of L Patella with Autol Sub, Perc Endo Approach', 55.47, 1);
insert into ARTICLE (name, description, price, category_id) values ('Oba', 'Bypass Common Bile Duct to Common Bile Duct, Open Approach', 64.76, 2);
insert into ARTICLE (name, description, price, category_id) values ('Voolia', 'Revision of Synthetic Substitute in Low Vein, Open Approach', 3.06, 2);
insert into ARTICLE (name, description, price, category_id) values ('Vinder', 'Removal of Drainage Device from Lower Back, Extern Approach', 52.41, 1);
insert into ARTICLE (name, description, price, category_id) values ('Centizu', 'Release Thymus, Percutaneous Approach', 24.44, 2);
insert into ARTICLE (name, description, price, category_id) values ('Youspan', 'Insertion of Spacer into Thor Jt, Perc Endo Approach', 43.0, 1);
insert into ARTICLE (name, description, price, category_id) values ('Twimm', 'Bypass R Fem Art to Post Tib Art w Autol Art, Open', 94.56, 2);
insert into ARTICLE (name, description, price, category_id) values ('Devpoint', 'Occlusion of Abd Aorta with Intralum Dev, Open Approach', 79.65, 1);
insert into ARTICLE (name, description, price, category_id) values ('Oozz', 'Supplement Right Middle Finger with Synth Sub, Open Approach', 35.69, 2);
insert into ARTICLE (name, description, price, category_id) values ('Kayveo', 'Removal of Drainage Device from L Lung, Perc Endo Approach', 34.98, 1);
insert into ARTICLE (name, description, price, category_id) values ('Skinder', 'Restrict of Esophageal Vein with Extralum Dev, Perc Approach', 36.34, 1);
insert into ARTICLE (name, description, price, category_id) values ('Dabvine', 'Destruction of Pharynx, Via Natural or Artificial Opening', 91.83, 1);
insert into ARTICLE (name, description, price, category_id) values ('Babblestorm', 'Repair Left Lung, Percutaneous Endoscopic Approach', 39.16, 2);
insert into ARTICLE (name, description, price, category_id) values ('Edgetag', 'Drainage of Left Ureter with Drainage Device, Perc Approach', 97.13, 2);
insert into ARTICLE (name, description, price, category_id) values ('Dynazzy', 'Insert Hybrid Ext Fix in L Low Femur, Perc Endo', 6.05, 1);
insert into ARTICLE (name, description, price, category_id) values ('Divape', 'Supplement Chest Subcu/Fascia w Synth Sub, Perc', 65.78, 2);
insert into ARTICLE (name, description, price, category_id) values ('Skimia', 'Bypass Lower Esophagus to Ileum, Perc Endo Approach', 17.69, 1);
insert into ARTICLE (name, description, price, category_id) values ('Twitterwire', 'Bypass L Hypogast Vein to Low Vein w Autol Vn, Perc Endo', 95.48, 1);
insert into ARTICLE (name, description, price, category_id) values ('Devpoint', 'Resection of Vulva, External Approach', 24.76, 1);
insert into ARTICLE (name, description, price, category_id) values ('Quimm', 'Bypass L Int Iliac Art to Low Ex Art w Autol Vn, Open', 50.85, 2);
insert into ARTICLE (name, description, price, category_id) values ('Babblestorm', 'Replacement of Low Art with Nonaut Sub, Perc Endo Approach', 37.04, 2);
insert into ARTICLE (name, description, price, category_id) values ('Rhyloo', 'Bypass Thor Aorta Asc to Carotid w Nonaut Sub, Open', 10.15, 1);
insert into ARTICLE (name, description, price, category_id) values ('Yozio', 'Removal of Extraluminal Device from Right Eye, Open Approach', 34.09, 1);
insert into ARTICLE (name, description, price, category_id) values ('Lazzy', 'Revise Radioact Elem in Uterus & Cervix, Perc Endo', 20.3, 2);
insert into ARTICLE (name, description, price, category_id) values ('Feedfish', 'Revision of Nonaut Sub in L Ear, Extern Approach', 4.61, 1);
insert into ARTICLE (name, description, price, category_id) values ('Thoughtstorm', 'Repair Left Hand Muscle, Open Approach', 80.95, 1);
insert into ARTICLE (name, description, price, category_id) values ('Zoomdog', 'Insertion of Spacer into R Metacarpophal Jt, Open Approach', 99.46, 2);

insert into USERS(username, password) values('user', '$2a$10$GRLdNijSQMUvl/au9ofL.eDwmoohzzS7.rmNSJZ.0FxO/BTk76klW'); --password
insert into USERS(username, password) values('admin', '$2a$10$GRLdNijSQMUvl/au9ofL.eDwmoohzzS7.rmNSJZ.0FxO/BTk76klW'); --password
insert into USERS(username, password) values('read_only', '$2a$10$GRLdNijSQMUvl/au9ofL.eDwmoohzzS7.rmNSJZ.0FxO/BTk76klW'); --password
insert into USERS(username, password) values('dummy', '$2a$10$GRLdNijSQMUvl/au9ofL.eDwmoohzzS7.rmNSJZ.0FxO/BTk76klW'); --password

insert into roles(name) values('USER');
insert into roles(name) values('ADMIN');
insert into roles(name) values('READ_ONLY');
insert into roles(name) values('DUMMY');

insert into role_user(application_user_id, role_id) values(1, 1);
insert into role_user(application_user_id, role_id) values(2, 1);
insert into role_user(application_user_id, role_id) values(2, 2);
insert into role_user(application_user_id, role_id) values(3, 3);